
color_map_options = [
    {"label": "COLORMAP_None", "value": "stop"},
    {"label": "COLORMAP_AUTUMN", "value": "0"},
    {"label": "COLORMAP_BONE", "value": "1"},
    {"label": "COLORMAP_JET", "value": "2"},
    {"label": "COLORMAP_WINTER", "value": "3"},
    {"label": "COLORMAP_RAINBOW", "value": "4"},
    {"label": "COLORMAP_OCEAN", "value": "5"},
    {"label": "COLORMAP_SUMMER", "value": "6"},
    {"label": "COLORMAP_SPRING", "value": "7"},
    {"label": "COLORMAP_COOL", "value": "8"},
    {"label": "COLORMAP_HSV", "value": "9"},
    {"label": "COLORMAP_PINK", "value": "10"},
    {"label": "COLORMAP_HOT", "value": "11"},
    {"label": "COLORMAP_PARULA", "value": "12"},
    {"label": "COLORMAP_MAGMA", "value": "13"},
    {"label": "COLORMAP_INFERNO", "value": "14"},
    {"label": "COLORMAP_PLASMA", "value": "15"},
    {"label": "COLORMAP_VIRIDIS", "value": "16"},
    {"label": "COLORMAP_CIVIDIS", "value": "17"},
    {"label": "COLORMAP_TWILIGHT", "value": "18"},
    {"label": "COLORMAP_TWILIGHT_SHIFTED", "value": "19"},
    {"label": "COLORMAP_TURBO", "value": "20"},
    {"label": "COLORMAP_DEEPGREEN", "value": "21"},
]